export const events = [
  {
    id: 1,
    title: "Annual Alumni Gala",
    date: "2025-12-15",
    time: "7:00 PM",
    location: "Grand Ballroom, Hyatt Hotel",
    venue: "Hyatt Regency Downtown",
    address: "123 Main Street, Downtown City, CA 90210",
    tags: ["Alumni Meetup", "Networking", "Formal", "Awards", "Dinner"],
    description:
      "Join us for an elegant evening celebrating our alumni achievements with dinner, awards, and networking opportunities.",
    type: "social",
    status: "upcoming",
    image:
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=400&h=250&fit=crop&crop=center",
    attendees: 250,
    registered: 120,
    featured: true,
    duration: "5 hours",
    highlights: ["3-Course Dinner", "Awards Ceremony", "Live Music", "Networking"],
    gallery: [
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=400&h=250&fit=crop&crop=center",
    ],
  },
  {
    id: 2,
    title: "Tech Industry Networking Summit",
    date: "2025-10-28",
    time: "6:30 PM",
    location: "Innovation Center",
    venue: "Innovation Hub Conference Hall",
    address: "45 Tech Park Road, Silicon Valley, CA 94025",
    tags: ["Networking", "Technology", "Startups", "Career"],
    description:
      "Connect with fellow alumni working in technology. Features panel discussions, career opportunities, and startup showcases.",
    type: "networking",
    status: "upcoming",
    image:
      "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=400&h=250&fit=crop&crop=center",
    attendees: 180,
    registered: 80,
    featured: false,
    duration: "4 hours",
    highlights: ["Panel Discussions", "Startup Showcases", "Career Networking"],
    gallery: [
      "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=400&h=250&fit=crop&crop=center",
    ],
  },
  {
    id: 3,
    title: "Alumni Mentorship Program Launch",
    date: "2025-11-12",
    time: "5:00 PM",
    location: "Campus Alumni Center",
    venue: "University Alumni Center",
    address: "789 College Avenue, Campus City, NY 10011",
    tags: ["Mentorship", "Career", "Networking", "Education"],
    description:
      "Launch of our new mentorship program connecting recent graduates with experienced professionals across industries.",
    type: "professional",
    status: "upcoming",
    image:
      "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=400&h=250&fit=crop&crop=center",
    attendees: 120,
    registered: 60,
    featured: false,
    duration: "3 hours",
    highlights: ["Program Launch", "Mentor-Mentee Introductions", "Panel Session"],
    gallery: [
      "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=400&h=250&fit=crop&crop=center",
    ],
  },
  {
    id: 4,
    title: "Homecoming Weekend Celebration",
    date: "2025-09-20",
    time: "10:00 AM",
    location: "Main Campus",
    venue: "University Grounds",
    address: "1 University Plaza, Hometown, IL 60601",
    tags: ["Reunion", "Sports", "Campus Tours", "Celebration"],
    description:
      "A weekend full of activities including campus tours, class reunions, and the homecoming game with special alumni activities.",
    type: "reunion",
    status: "upcoming",
    image:
      "https://unsplash.com/photos/a-blue-and-white-calendar-with-red-squares-VPwAFRQTBZM?w=400&h=250&fit=crop&crop=center",
    attendees: 500,
    registered: 400,
    featured: true,
    duration: "2 days",
    highlights: ["Campus Tours", "Class Reunions", "Homecoming Game"],
    gallery: [
      "https://unsplash.com/photos/a-blue-and-white-calendar-with-red-squares-VPwAFRQTBZM?w=400&h=250&fit=crop&crop=center",
    ],
  },
  {
    id: 5,
    title: "Career Fair & Industry Expo",
    date: "2025-08-15",
    time: "2:00 PM",
    location: "Student Union Building",
    venue: "University Student Union",
    address: "456 University Avenue, College Town, TX 73301",
    tags: ["Career", "Expo", "Employers", "Students"],
    description:
      "Alumni-hosted career fair featuring opportunities across various industries and experience levels with top employers.",
    type: "professional",
    status: "upcoming",
    image:
      "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&h=250&fit=crop&crop=center",
    attendees: 300,
    registered: 210,
    featured: false,
    duration: "6 hours",
    highlights: ["Employer Booths", "Workshops", "Networking"],
    gallery: [
      "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&h=250&fit=crop&crop=center",
    ],
  },
  {
    id: 6,
    title: "Summer Social Mixer",
    date: "2025-07-10",
    time: "7:00 PM",
    location: "Rooftop Terrace Venue",
    venue: "Skyline Rooftop Terrace",
    address: "789 Sunset Boulevard, Los Angeles, CA 90001",
    tags: ["Social", "Music", "Drinks", "Networking"],
    description:
      "Casual summer gathering with drinks, appetizers, and great company under the stars with live music.",
    type: "social",
    status: "on-going",
    image:
      "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400&h=250&fit=crop&crop=center",
    attendees: 150,
    registered: 90,
    featured: false,
    duration: "4 hours",
    highlights: ["Live Music", "Drinks & Appetizers", "Networking"],
    gallery: [
      "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400&h=250&fit=crop&crop=center",
    ],
  },
];
